const images = {
    package: require('./package.svg'),
    bike: require('./bike.svg'),
    frame: require("./Frame.svg"),
    vector: require("./Vector.svg"),
    add_notes: require("./add_notes.svg"),
    backArrow: require("./backArrow.svg"),
    forwardArrow: require("./forwardArrow.svg"),
    lockOpen: require("./lock_open.svg"),
    settingsBell: require("./settingsBell.svg"),
    home: require("./Home.webp"),
    profile: require("./Profile.webp"),
    calendar: require("./calendar.webp"),
    check: require("./check.svg"),
    minus: require("./closeAccordion.svg"),
    plus: require("./openAccordion.svg"),
    car: require("./car.svg"),
    greenTick: require("./greenTick.svg"),
    truck: require("./truck.svg"),
    warning: require("./warning.svg"),
    exclamation: require("./exclamation.svg"),
    exclamationWhite: require("./exclamationWhite.svg"),
    dollar: require("./dollar.svg"),
    location: require("./location.svg"),
    bookingLogo: require("./bookingLogo.svg"),
    camera: require("./camera_alt_24px.svg"),
    downarrow: require("./arrow_forward_ios.svg"),
    greenIndicator: require("./greenIndicator.svg"),
    small: require("./Small.svg"),
    vehicles: require("./vehicles.svg"),
    documents: require("./documents.svg"),
    account_balance: require("./account_balance.svg"),
    setting: require("./setting.svg"),
    faq: require("./faq.svg"),
    invitation: require("./invitation.svg"),
    signout: require("./signout.svg"),
    logout: require("./logout.svg"),
    credit_card: require("./credit_card.svg"),
    spark: require("./spark.svg"),
    time: require("./time.svg"),
    dummyBarCode: require("./dummyBarCode.svg"),
    dummyCompany: require("./dummyCompany.svg"),

};

export default images;