const images = {
    package: require('./package.svg'),
    bike: require('./bike.svg'),
    frame: require("./Frame.svg"),
    vector: require("./Vector.svg"),
    add_notes: require("./add_notes.svg"),
    backArrow: require("./backArrow.svg"),
    forwardArrow: require("./forwardArrow.svg"),
    lockOpen: require("./lock_open.svg"),
    settingsBell: require("./settingsBell.svg"),
    home: require("./Home.webp"),
    profile: require("./Profile.webp"),
    calendar: require("./calendar.webp"),
    check: require("./check.svg"),
    warning: require("./warning.svg"),
    exclamation: require("./exclamation.svg"),
    dollar: require("./dollar.svg"),
    location: require("./location.svg"),
    bookingLogo: require("./bookingLogo.svg"),
    camera: require("./camera_alt_24px.svg"),
    downarrow: require("./arrow_forward_ios.svg"),
    ellipse: require("./Ellipse 122.svg"),
    small: require("./Small.svg"),
};

export default images;