export const API_URLS = {
  LOGIN: 'login',
  register: 'register',
  getAllModules: 'get-all-modules',
  getUserModules: 'get-user-modules',
  getModuleDetail: 'get-module-detail',
  getTopics: 'get-topics',
  getTopicLesson: 'get-topic-lesson',
  getOtherLesson: 'get-other-lesson',
  lessonDone: 'lesson-done',
  userTopicQuestions: 'user-topic-questions',
  startTopicTest: 'start-topic-test',
  topicNextQuestion: 'topic-next-question',
  topicPrevQuestion: 'topic-prev-question',
  saveMyQuestion: 'save-my-question',
  questionNote: 'question-note',
  questionHelpText: 'question-helptext',
  getUserModuleHistory: 'get-user-modules-history',
  changeUserPassword: 'change-user-password',
  updateUserProfile: 'update-user-profile',
  getProfile: 'get-profile',
  topicPracticeReport: 'topic-practice-report',
  startMockTest: 'start-mock-test',
  nextMockQuestion: 'next-mock-question',
  prevMockQuestion: 'prev-mock-question',
  endTopicTest: 'end-topic-test',
  hazardPreparation: 'hazard-preparation',
  hazardPreparationVideos: 'hazard-preparation-videos',
  getGroupVideos: 'get-group-videos',
  startVideoTest: 'start-video-test',
  updateUserDeleteStatus: 'update-user-delete-status',
  forgetPassword: 'forget-password',
  mockTestReport: 'mock-test-report',
  getAnswerView: 'get-answer-video',
  hazardPerceptionTestReport: 'hazard-perception-test-report',
  saveVideo: 'save-video',
  exceedClicks: 'exceed-clicks',
  clickedHotspot: 'clicked-hotspot',
  endVideoTest: 'end-video-test',
  getQuestionNote: 'get-question-note',
  getNotification: 'get-notification',
  deleteNotification: 'delete-notification',
  deleteAllNotification: 'delete-all-notification',
  getAllCasestudy:"get-all-casestudy",
  caseStudyTestDetail:"casestudy-test-detail",
  startCaseStudyTest:"start-casestudy-test",
  nextCaseStudyQuestion: 'next-casestudy-question',
  prevCaseStudyQuestion: 'prev-casestudy-question',
  endCsTopicTest: 'end-cstopic-test',
  endCsMockTest: 'end-csmock-test',
  startCsMockTest: "start-csmock-test",
  nextCsMockQuestion: 'next-csmock-question',
  prevCsMockQuestion: 'prev-csmock-question',
  getAllCaseStudyTest:'get-all-casestudy-test',
  getAllCsMockTest:'get-all-csmock-test',
  getAvailableModules:'get-available-modules',
  modulePayment:'module-payment'

};
