import { moderateScale } from '@scale';

export const fontFamily = {
  //// inter fonts
  Black: 'AvenirLTStd-Black',
  BlackOblique: 'AvenirLTStd-BlackOblique',
  Book: 'AvenirLTStd-Book',
  BookOblique: 'AvenirLTStd-BookOblique',
  Heavy: 'AvenirLTStd-Heavy',
  HeavyOblique: 'AvenirLTStd-HeavyOblique',
  Light: 'AvenirLTStd-Light',
  LightOblique: 'AvenirLTStd-LightOblique',
  Medium: 'AvenirLTStd-Medium',
  MediumOblique: 'AvenirLTStd-MediumOblique',
  Oblique: 'AvenirLTStd-Oblique',
  Roman: 'AvenirLTStd-Roman',
};

export const fontSize = {
  fontSize_8: moderateScale(8),
  fontSize_10: moderateScale(10),
  fontSize_11: moderateScale(11),
  fontSize_12: moderateScale(12),
  fontSize_13: moderateScale(13),
  fontSize_14: moderateScale(14),
  fontSize_15: moderateScale(15),
  fontSize_16: moderateScale(16),
  fontSize_17: moderateScale(17),
  fontSize_18: moderateScale(18),
  fontSize_19: moderateScale(19),
  fontSize_20: moderateScale(20),
  fontSize_22: moderateScale(22),
  fontSize_24: moderateScale(24),
  fontSize_26: moderateScale(26),
  fontSize_28: moderateScale(28),
  fontSize_30: moderateScale(30),
  fontSize_32: moderateScale(32),
  fontSize_34: moderateScale(34),
  fontSize_40: moderateScale(40),
  fontSize_48: moderateScale(48),
  fontSize_50: moderateScale(50),
  fontSize_52: moderateScale(52),
  fontSize_54: moderateScale(54),
  fontSize_56: moderateScale(56),
  fontSize_58: moderateScale(58),
  fontSize_60: moderateScale(60),
  fontSize_66: moderateScale(66),
};
